In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sample sentences
sent = ['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
## Define Vocabulary size
voc_size = 10000

In [5]:
### One hot representation
one_hot_repr = [one_hot(word, voc_size) for word in sent]
one_hot_repr

[[1049, 9558, 6376, 5961],
 [1049, 9558, 6376, 9718],
 [1049, 4735, 6376, 2757],
 [139, 823, 6458, 3091, 6283],
 [139, 823, 6458, 3091, 1981],
 [5324, 1049, 2400, 6376, 4956],
 [2494, 7184, 3370, 3091]]

In [8]:
# word embeddings

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 1049, 9558, 6376, 5961],
       [   0,    0,    0,    0, 1049, 9558, 6376, 9718],
       [   0,    0,    0,    0, 1049, 4735, 6376, 2757],
       [   0,    0,    0,  139,  823, 6458, 3091, 6283],
       [   0,    0,    0,  139,  823, 6458, 3091, 1981],
       [   0,    0,    0, 5324, 1049, 2400, 6376, 4956],
       [   0,    0,    0,    0, 2494, 7184, 3370, 3091]], dtype=int32)

In [10]:
## Feature Representation
dim = 10

In [ ]:
Embedding

In [15]:
model = Sequential()
model.add(Embedding(input_dim = voc_size, output_dim = 10, input_length=sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 232ms/step


array([[[-0.04254466, -0.02183082,  0.03727639,  0.02927912,
         -0.0121192 , -0.02165768, -0.02277916, -0.00090199,
         -0.02729297, -0.03134902],
        [-0.04254466, -0.02183082,  0.03727639,  0.02927912,
         -0.0121192 , -0.02165768, -0.02277916, -0.00090199,
         -0.02729297, -0.03134902],
        [-0.04254466, -0.02183082,  0.03727639,  0.02927912,
         -0.0121192 , -0.02165768, -0.02277916, -0.00090199,
         -0.02729297, -0.03134902],
        [-0.04254466, -0.02183082,  0.03727639,  0.02927912,
         -0.0121192 , -0.02165768, -0.02277916, -0.00090199,
         -0.02729297, -0.03134902],
        [ 0.04446672,  0.03146571,  0.02065916,  0.04460274,
         -0.00693151, -0.02926201,  0.02049455, -0.03913392,
         -0.03230287,  0.04087642],
        [ 0.04469557,  0.03168067,  0.01052998, -0.04962503,
         -0.00436815,  0.00670146,  0.02816873,  0.02344019,
          0.00186593, -0.02336348],
        [-0.04960876, -0.02932414, -0.01265657, -0.0

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 1049, 9558, 6376, 5961], dtype=int32)

In [24]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[[-0.04254466, -0.02183082,  0.03727639,  0.02927912,
         -0.0121192 , -0.02165768, -0.02277916, -0.00090199,
         -0.02729297, -0.03134902],
        [-0.04254466, -0.02183082,  0.03727639,  0.02927912,
         -0.0121192 , -0.02165768, -0.02277916, -0.00090199,
         -0.02729297, -0.03134902],
        [-0.04254466, -0.02183082,  0.03727639,  0.02927912,
         -0.0121192 , -0.02165768, -0.02277916, -0.00090199,
         -0.02729297, -0.03134902],
        [-0.04254466, -0.02183082,  0.03727639,  0.02927912,
         -0.0121192 , -0.02165768, -0.02277916, -0.00090199,
         -0.02729297, -0.03134902],
        [ 0.04446672,  0.03146571,  0.02065916,  0.04460274,
         -0.00693151, -0.02926201,  0.02049455, -0.03913392,
         -0.03230287,  0.04087642],
        [ 0.04469557,  0.03168067,  0.01052998, -0.04962503,
         -0.00436815,  0.00670146,  0.02816873,  0.02344019,
          0.00186593, -0.02336348],
        [-0.04960876, -0.02932414, -0.01265657, -0.0